--[==[
stdlib.lua — pure-Lua T1 stdlib (Task 7 of the Lua mapping-engine
feasibility project). Ports the T1-relevant subset of `MappingCategory`
(docs/specs/mapping-language-core.md section 4.1), `GroovyNode`'s own
convenience methods (section 4.2) and plain String/Groovy-GDK methods
(section 4.3) that Task 2's corpus scan found in the T1 tier.

Surface: every function takes a string, a Task-6 node
(engine/node.lua), or a Task-6 absorber as its first ("receiver")
argument. It is coerced via `to_text`: a string passes through, a
node/absorber is reduced via its own `:text()` (an absorber's `:text()` is
"", per node.lua), and a plain Lua array (standing in for a Groovy
`List`/`NodeList`) renders as `"[a, b]"` (spec section 1 / 4.3).

DELIBERATE DEVIATION from spec section 5.2's per-function null table —
documented here and in task-7-report.md, not hidden:

  A nil or absorber *receiver* (first argument) is null-safe: it coerces to
  "" and the function proceeds as if called on the empty string, rather
  than reproducing Groovy's NPE-at-call-site. This is what the brief's own
  worked example specifies (`assert.equal("", stdlib.capitalize(nil))`,
  task-7-brief.md step 1) and it keeps the engine total — a mapping.lua
  script generated by Task 8 must be able to call these functions on the
  result of a Task-6 navigation miss without crashing, exactly as Task 6's
  absorber was built to make chained navigation total. Reproducing every
  NPE from section 5.2 would reintroduce the crash-on-absence behaviour
  Task 6 deliberately engineered away.

  A nil *later* argument (a regex/delimiter/needle/replacement — a
  code-level literal from generated mapping source, not absent input data)
  is NOT absorbed: it raises a Lua error. This preserves the spirit of
  section 5.2's "null later arg" rows (also NPE in Groovy) for what is
  actually a programmer/codegen bug rather than a data-absence case.

  `sanitizeURN` keeps its explicit null-safe "" behaviour (spec 4.1 #23) —
  here that coincides with the general receiver rule, so there is no
  special case to write.

  `asBoolean` was already null-safe in Groovy ("not dispatched — null is
  falsy", spec 5.2), so no deviation there either.

Explicitly OUT OF SCOPE for this task (documented in task-7-report.md, not
silently dropped):
  - `getAt` (spec 4.1 #8): throws unconditionally in the reference impl and
    is superseded by the `node['x']` open question (spec 2.4); not needed
    by any T1 builder script.
  - `plus`/`or` (spec 4.1 #12/#13) and `multiply` with a delimiter
    (#15/#16): operate on `List<GroovyNode>` via `flatten`/`getValueNodes`,
    infrastructure Task 6 did not expose (only `get`/`get_`, not a
    recursive multi-match collector or a live "*" children view). Not in
    Task 2's top-20 T1 constructs.
  - `multiply`/`power`/`rightShift` with a closure (#14/#17/#18): the spec
    itself marks these "[spike: out of scope, sub-project 2]" (section
    4.4) — closures are a T2 construct.
  - `calculateAge`/`calculateAgeRange` (spec 4.7): standard mapping
    functions loaded from a resource file at runtime, not part of the
    MappingCategory/GroovyNode/String stdlib this task ports.
  - `lookupX`/dictionary lookups (spec 7.3): Facts & lookups machinery,
    generated per-mapping, not a fixed stdlib function.
]==]

local M = {}

-- Coerces a stdlib argument: string passes through; a node/absorber (any
-- table exposing :text()) reduces to its text; a plain Lua array (no
-- :text method — standing in for a Groovy List/NodeList) renders
-- "[elem, elem]" recursively (spec section 1: NodeList.toString() is
-- ArrayList's `[a, b]`); nil stays nil (the one case callers must
-- distinguish, per the module header's null-safety design).
local function to_text(v)
  if v == nil then
    return nil
  end
  local t = type(v)
  if t == "string" then
    return v
  end
  if t == "table" then
    if v.text then
      return v:text()
    end
    local parts = {}
    for i, item in ipairs(v) do
      parts[i] = to_text(item)
      if parts[i] == nil then
        parts[i] = "null"
      end
    end
    return "[" .. table.concat(parts, ", ") .. "]"
  end
  return tostring(v)
end
M.to_text = to_text

-- Null-safe coercion for a receiver argument: nil/absorber -> "" (see
-- module header for why this diverges from spec 5.2's NPE rows).
local function receiver_text(v)
  local s = to_text(v)
  if s == nil then
    return ""
  end
  return s
end

-- A later (code-level) argument must not be nil; nil here is a programmer
-- error, not absent data (see module header).
local function require_arg(v, fname, argname)
  if v == nil then
    error(fname .. ": nil " .. argname .. " (not a data-absence case — a literal argument was expected)", 3)
  end
  return v
end

--------------------------------------------------------------------------
-- MappingCategory (spec 4.1)
--------------------------------------------------------------------------

-- #1 replaceAll(s, regex, replacement) — Lua pattern, not java.util.regex;
-- translation from Groovy regex to a Lua pattern is the converter's job
-- (Task 8), per spec section 9.4.
function M.replaceAll(s, pattern, repl)
  local str = receiver_text(s)
  require_arg(pattern, "replaceAll", "pattern")
  require_arg(repl, "replaceAll", "replacement")
  return (str:gsub(pattern, repl))
end

local function raw_split(str, pattern)
  if str == "" then
    return { "" }
  end
  local parts = {}
  local pos = 1
  local len = #str
  while true do
    local s, e = str:find(pattern, pos)
    if not s then
      parts[#parts + 1] = str:sub(pos)
      break
    end
    if e < s then
      -- zero-width match: consume one character to avoid looping forever
      parts[#parts + 1] = str:sub(pos, s)
      pos = s + 1
    else
      parts[#parts + 1] = str:sub(pos, s - 1)
      pos = e + 1
    end
    if pos > len + 1 then
      parts[#parts + 1] = ""
      break
    end
  end
  return parts
end

-- #2/#3 split(s, regex[, limit]) — JDK trailing-empty-removal semantics
-- when no limit (or limit == 0) is given; an explicit positive limit caps
-- the result count, with the final element holding the unsplit remainder.
-- Simplification: a negative limit is treated the same as "no limit"
-- (JDK's negative-limit "no trailing removal" nuance is not reproduced —
-- not observed in the T1 corpus, see task-7-report.md).
function M.split(s, pattern, limit)
  local str = receiver_text(s)
  require_arg(pattern, "split", "pattern")

  if limit and limit > 0 then
    local parts = {}
    local pos = 1
    local len = #str
    while #parts < limit - 1 do
      local fs, fe = str:find(pattern, pos)
      if not fs then
        break
      end
      if fe < fs then
        parts[#parts + 1] = str:sub(pos, fs)
        pos = fs + 1
      else
        parts[#parts + 1] = str:sub(pos, fs - 1)
        pos = fe + 1
      end
      if pos > len + 1 then
        break
      end
    end
    parts[#parts + 1] = str:sub(pos)
    return parts
  end

  local parts = raw_split(str, pattern)
  if #parts > 1 then
    while #parts > 0 and parts[#parts] == "" do
      table.remove(parts)
    end
  end
  return parts
end

-- #4 matches(s, regex) — whole-string match.
function M.matches(s, pattern)
  local str = receiver_text(s)
  require_arg(pattern, "matches", "pattern")
  local fs, fe = str:find(pattern)
  return fs == 1 and fe == #str
end

-- #7 asBoolean(list) — list truth: empty -> false; a single element that is
-- itself a plain (non-node) list -> that list's truth; otherwise true.
-- nil is falsy without error (Groovy never dispatches on a null receiver).
local function is_plain_list(v)
  return type(v) == "table" and v.text == nil and v.__gstring == nil
end

function M.asBoolean(list)
  if list == nil then
    return false
  end
  if not is_plain_list(list) then
    return true
  end
  local n = #list
  if n == 0 then
    return false
  end
  if n == 1 and is_plain_list(list[1]) then
    return M.asBoolean(list[1])
  end
  return true
end

-- #19/#20/#21 sanitize(node/list/text) — the three Groovy overloads unify
-- here through `to_text`'s coercion (node -> text, list -> "[a, b]", text
-- -> itself). Collapses newlines to spaces then runs of spaces to one;
-- does NOT trim and does NOT strip apostrophes.
function M.sanitize(v)
  local s = receiver_text(v)
  s = s:gsub("[\r\n]+", " ")
  s = s:gsub(" +", " ")
  return s
end

-- #22 sanitizeURI(object) — percent-encodes ONLY space -> %20, [ -> %5B,
-- ] -> %5D, \ -> %5C; nothing else is touched. NOT a general
-- percent-encoder.
function M.sanitizeURI(v)
  local s = receiver_text(v)
  s = s:gsub(" ", "%%20")
  s = s:gsub("%[", "%%5B")
  s = s:gsub("%]", "%%5D")
  s = s:gsub("\\", "%%5C")
  return s
end

-- #23 sanitizeURN(object) — the one function that is null-safe by an
-- explicit guard in the reference implementation too: replaces each of
-- `: / _ space [ ] \` with '-' and collapses runs of '-'.
function M.sanitizeURN(v)
  local s = receiver_text(v)
  s = s:gsub("[:/_%[%]\\ ]", "-")
  s = s:gsub("%-+", "-")
  return s
end

--------------------------------------------------------------------------
-- GroovyNode convenience methods (spec 4.2) + plain String methods
-- (spec 4.3), unified: a node receiver coerces to its `:text()`, so these
-- are single implementations shared by both families.
--------------------------------------------------------------------------

-- #9 indexOf(node, s) / plain String indexOf(s) — LITERAL substring search
-- (Java's String.indexOf is not a regex method), 0-based, -1 when absent.
function M.indexOf(v, needle)
  local str = receiver_text(v)
  require_arg(needle, "indexOf", "needle")
  local fs = str:find(needle, 1, true)
  if not fs then
    return -1
  end
  return fs - 1
end

-- #10/#11 substring(node, from[, to]) — Java 0-based, exclusive-end
-- semantics; out-of-range raises (StringIndexOutOfBoundsException
-- equivalent).
function M.substring(v, from, to)
  local str = receiver_text(v)
  local len = #str
  if to == nil then
    if from < 0 or from > len then
      error("substring: index " .. tostring(from) .. " out of range for length " .. len, 2)
    end
    return str:sub(from + 1)
  end
  if from < 0 or to > len or from > to then
    error("substring: range [" .. from .. "," .. to .. ") out of bounds for length " .. len, 2)
  end
  return str:sub(from + 1, to)
end

-- replace(a, b) — LITERAL (non-regex) replacement, distinct from
-- replaceAll.
function M.replace(v, a, b)
  local str = receiver_text(v)
  require_arg(a, "replace", "target")
  require_arg(b, "replace", "replacement")
  if a == "" then
    return str
  end
  local parts = {}
  local pos = 1
  local alen = #a
  while true do
    local s = str:find(a, pos, true)
    if not s then
      parts[#parts + 1] = str:sub(pos)
      break
    end
    parts[#parts + 1] = str:sub(pos, s - 1)
    parts[#parts + 1] = b
    pos = s + alen
  end
  return table.concat(parts)
end

-- capitalize() — Groovy GDK: upper-cases the first character only.
function M.capitalize(v)
  local str = receiver_text(v)
  if str == "" then
    return ""
  end
  return str:sub(1, 1):upper() .. str:sub(2)
end

-- trim() — strips ASCII whitespace from both ends. (Simplification: Java's
-- trim() strips any char <= U+0020, Lua's %s is the practical ASCII
-- whitespace subset; not observed to diverge on the T1 corpus.)
function M.trim(v)
  local str = receiver_text(v)
  return (str:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- toLowerCase() / toUpperCase() — Lua's string.lower/upper is byte-based
-- (ASCII); this is the "pin to root locale" behaviour spec 4.3
-- recommends, not the JVM's default-locale mapping.
function M.toLowerCase(v)
  return receiver_text(v):lower()
end

function M.toUpperCase(v)
  return receiver_text(v):upper()
end

-- toString() — identity for a string; a node's text; "[a, b]" for a plain
-- list (spec section 1/2.6).
function M.toString(v)
  return receiver_text(v)
end

-- toInteger() — Groovy GDK Integer.valueOf after trim; throws on junk
-- (including "", which is what a nil receiver coerces to and Groovy's own
-- "".toInteger() also throws on — no special-casing needed here).
function M.toInteger(v)
  local trimmed = M.trim(v)
  if trimmed:match("^[+-]?%d+$") then
    return math.floor(tonumber(trimmed))
  end
  error("toInteger: NumberFormatException for input string: \"" .. trimmed .. "\"", 2)
end

-- contains(s) / startsWith(s) / endsWith(s)
function M.contains(v, needle)
  local str = receiver_text(v)
  require_arg(needle, "contains", "needle")
  return str:find(needle, 1, true) ~= nil
end

function M.startsWith(v, prefix)
  local str = receiver_text(v)
  require_arg(prefix, "startsWith", "prefix")
  return str:sub(1, #prefix) == prefix
end

function M.endsWith(v, suffix)
  local str = receiver_text(v)
  require_arg(suffix, "endsWith", "suffix")
  if #suffix == 0 then
    return true
  end
  return str:sub(-#suffix) == suffix
end

-- isEmpty() — length zero; does NOT trim.
function M.isEmpty(v)
  return #receiver_text(v) == 0
end

-- size() — on a String/node, character/text length; on a plain list,
-- element count (spec 4.2/4.3: node.size() is a documented trap — it is
-- NOT a child count).
function M.size(v)
  if is_plain_list(v) then
    return #v
  end
  return #receiver_text(v)
end

-- join(sep) — Groovy GDK on a collection; stringifies each element. A nil
-- list is a programmer error (nothing to join), not absent data.
function M.join(list, sep)
  require_arg(list, "join", "list")
  local parts = {}
  for i, item in ipairs(list) do
    local t = to_text(item)
    parts[i] = t == nil and "null" or t
  end
  return table.concat(parts, sep or "")
end

--------------------------------------------------------------------------
-- Template-string ("GString") support — Builder output spec section 3.4
-- suppressIfAllVariablesEmpty, the structural hazard flagged for this task.
--------------------------------------------------------------------------

-- gs(parts, slot_texts) — builds a template-string value for
-- builder.lua's content/attribute resolution. `parts` is the array of
-- literal fragments (#parts == #slot_texts + 1, as usual for an
-- interpolated string split around its slots). `slot_texts` is the
-- ALREADY-STRINGIFIED text of each interpolated slot, in Groovy's own
-- interpolation rules (spec 4.6: a node renders its text, a list renders
-- "[a, b]", and — this is the caller's responsibility, not gs's — a nil
-- value must be pre-rendered as the literal word "null", never passed as
-- a real Lua nil, so that the slot_texts array can never contain a hole).
-- Task 8's codegen is expected to build slot_texts via
-- `stdlib.to_text(v) or "null"` per slot.
--
-- Returns { __gstring = true, text = <rendered>, suppressed = <bool> }.
-- Per spec 3.4: suppressed is true only when there is at least one slot
-- AND every slot's trimmed text is empty. A zero-slot template (a plain
-- literal with no interpolation) is never suppressed.
function M.gs(parts, slot_texts)
  slot_texts = slot_texts or {}
  local rendered = {}
  for i = 1, #parts do
    rendered[#rendered + 1] = parts[i]
    local t = slot_texts[i]
    if t ~= nil then
      rendered[#rendered + 1] = t
    end
  end

  local suppressed = #slot_texts > 0
  for _, t in ipairs(slot_texts) do
    if M.trim(t) ~= "" then
      suppressed = false
      break
    end
  end

  return { __gstring = true, text = table.concat(rendered), suppressed = suppressed }
end

return M
